import Link from "next/link"

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <nav className="w-full p-2">
          <ul className="flex gap-4">
            <li className="hover:text-blue-600">
              <Link href={"/"}>Login</Link>
            </li>
            <li className="hover:text-blue-600">
              <Link href={"/register"}>Register</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
